{% set version = '0.2.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytree
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidytree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytree/tidytree_{{ version }}.tar.gz
  sha256: 627193a4cf5c18a9236b102ed38fc051d4d9a5c03fd3575930679e4b374fa6eb

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: ggtree, knitr, prettydoc, testthat, treeio
requirements:
  build:

  host:
    - r-base
    - r-ape
    - r-dplyr
    - r-lazyeval
    - r-magrittr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-ape
    - r-dplyr
    - r-lazyeval
    - r-magrittr
    - r-rlang
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('tidytree')"           # [not win]
    - "\"%R%\" -e \"library('tidytree')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/tidytree
  license: Artistic-2.0
  summary: Phylogenetic tree generally contains multiple components including node, edge, branch
    and associated data. 'tidytree' provides an approach to convert tree object to tidy
    data frame as well as provides tidy interfaces to manipulate tree data.
  license_family: OTHER

extra:
  recipe-maintainers:
    - conda-forge/r
