{% set version = "0.3.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidytree
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidytree_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidytree/tidytree_{{ version }}.tar.gz
  sha256: b3e9eb7e65188ddfd6071e55eba51a2915087000239da0cbb3784ff03fa9d7be

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ape
    - r-dplyr
    - r-lazyeval
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect
  run:
    - r-base
    - r-ape
    - r-dplyr
    - r-lazyeval
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-tidyselect

test:
  commands:
    - $R -e "library('tidytree')"           # [not win]
    - "\"%R%\" -e \"library('tidytree')\""  # [win]

about:
  home: https://yulab-smu.github.io/treedata-book/
  license: Artistic-2.0
  summary: Phylogenetic tree generally contains multiple components including node, edge, branch and associated data. 'tidytree' provides an approach to convert tree object to tidy data frame as well as provides tidy interfaces to manipulate tree data.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: tidytree
# Title: A Tidy Tool for Phylogenetic Tree Data Manipulation
# Version: 0.2.8
# Authors@R: c( person("Guangchuang", "Yu",   email = "guangchuangyu@gmail.com", role = c("aut", "cre", "cph"), comment = c(ORCID = "0000-0002-6485-8781")), person("Bradley", "Jones",    email = "brj1@sfu.ca",             role = "ctb"), person("Zebulun", "Arendsee", email = "zbwrnz@gmail.com",        role = "ctb") )
# Description: Phylogenetic tree generally contains multiple components including node, edge, branch and associated data. 'tidytree' provides an approach to convert tree object to tidy data frame as well as provides tidy interfaces to manipulate tree data.
# Depends: R (>= 3.4.0)
# Imports: ape, dplyr, lazyeval, magrittr, methods, rlang, tibble, utils
# Suggests: ggtree, knitr, prettydoc, testthat, treeio
# VignetteBuilder: knitr
# ByteCompile: true
# License: Artistic-2.0
# URL: https://yulab-smu.github.io/treedata-book/
# BugReports: https://github.com/YuLab-SMU/tidytree/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-09-27 03:55:53 UTC; ygc
# Author: Guangchuang Yu [aut, cre, cph] (<https://orcid.org/0000-0002-6485-8781>), Bradley Jones [ctb], Zebulun Arendsee [ctb]
# Maintainer: Guangchuang Yu <guangchuangyu@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-09-27 07:10:03 UTC
