appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: oPzAi4MxhyEwqvN6zoR/f/b3YZ5brE3mdORJI5cWE70wy76bemuiDPEYYfK9Ey3I+yCvv51jc+u78VaugeYFIv1dzI/HrR81J8w2L8JrgI41OyXx4C33v+/i3WqQjasYMgsQP7bcjeWOsn2SQGI/CQAj5n2TMLgMODTMErTXmHN2j8heDgF9SS32zc11JVMQCxNYWq/95BcmB0rXrqLEYTsodzMaoC2Es1rySIBnnRp9JvT+y7TUNKZGJIv2nMz6sibC4nvjaktJI0qQFhZrEdkSsVSR4dwycrawK9GPpDUy+bCe6baLRz/EKTuVBQSUnfa6J4PQqfUYPw7jR+6kx4wF3mnxx8QlnpEAGKn6983JE5VEKjdWjfyvNjPXl5ZQPgDEfaJi8/Ph+k86CJK+iyl1/P1xADL5+LnRByeAGuLBbrJ9ZSGldyDKk7QmZjvKak/iynFQApTbPY5qsfIY3BemFA3x2ihv2bvdYPH0c0cFJFHchOl1N+fUoN2l68jzz27ytBEbLJzKTVfs1vJz7Vqa0L65JM9fbAVTplU8J+94BGmQiLoIIpNQm1eAFh+4fCJRtvYcs220WIW18MigtOhx8MRCFTRiDg7LIJ9qzWMfDQaOXCEpR6XVII+T19QJeYWt7yEZ30G977DrDOkc/THLHH+4ysetlg2LbWxOfNI=}
